# Generated by Django 2.1 on 2018-11-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_auto_20181114_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='prop',
            name='home_type',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
